[build]
  command = "parcel build src/index.html --out-dir dist"
  publish = "dist/"

[dev]
  command = "npm start"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

[context.production.environment]
  NODE_ENV = "production"
  DATABASE_URL = "your-database-url"

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"